name: Azure Pipelines
variables:
  python.version: '3.7.6'
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted Ubuntu 1604
    steps:
    # Needed for Terraform VM deployment
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: 'KNOWN_HOSTS_STRING'
        sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDPduqXrhKK7kOHubixvfMyCNzymE2osf0rLJnzigM7vIS/2mDFPPdbCmMwEu1VcntrulsrAswPFOgJFnc4Ll5d9lv83UXxVnPjw1I6/cLq0PoLE0Lw8t98X80PRjB5shOcH51Bfb34uPcA3OI6bv+zZ0JyXNQowB/FKHuvDyw71ZUfYkqP51QzTgwsMfIUUeRKmJKMYapEFz4UiKPIdgHM3Jqw6bi/3HiD8WtDlzIV533FeI4MpqruRPBD9Gvz/BFD5N+fulDWdN+JbD8HTTrJuDFE2Bd4PCMBPgTer7jzEEx3MP2DriTbw3wyxIDlwefjWPkeOlWuwe8T1riw0hUauV0nMLnVUolb11kl8T2WP4TwxgmS6TWHulU9XR/QTwA5HXkpzE72TMeVFTTACXeEFFBozoypHFb0rICAMSm46otEiu2yYz9SywjquSsatTy+Bn/545LB2BaLiFxttvfJD/73G9HbHqikUlKy+8bsnqHMrjKlbsvMZjZjKiskpCRmVvky8610RFEscXlvzH+fILx6NYYI4ahesl2KrKBaMwpt+MO3DslzJzfOOv/7UITkegA6mQBcBnvECNKe/XqklPA8LIkMdjyHRBF5PiEsFaWhTtJTEy72x/5GmVj65Ek3OuuxxExu3bidRfwCfqf/JkIqB9ngxonVJVkOLEV81Q== qian@cc-50e985af-5dbf9bc6b5-m8sk9'
        sshKeySecureFile: 'id_rsa'
    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'myazuresub'
        backendAzureRmResourceGroupName: 'rg_default'
        backendAzureRmStorageAccountName: 'qzstore1'
        backendAzureRmContainerName: 'qzcontainer1'
        backendAzureRmKey: 'terraform.tfstate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environments/test'
    - task: TerraformTaskV2@2
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'myazuresub'
    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: 'fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload Package'
      artifact: drop-fakerestapi
- stage:
  jobs:
  - deployment: FakeRestAPI
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'TEST'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: 'myazuresub2'
              appName: 'qzapp-AppService'
              appType: webApp
              package: $(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip
  # - deployment: VMDeploy
  #   displayName: NAME
  #   environment:
  #     name:  ENVIRONMENT NAME
  #     resourceType: VirtualMachine
  #     tags: TAG NAME
  #   strategy:
  #     runOnce:
  #       deploy:
  #         steps:
  #         - task: Bash@3
  #           inputs:
  #             targetType: 'inline'
  #             script: |
  #               #! /bin/bash
                
  #               sudo apt-get upgrade -y
  #               sudo apt-get install python3-pip -y
  #               sudo apt-get install unzip -y
  #               sudo apt-get install -y chromium-browser
  #               pip3 install selenium
  #               export PATH=$PATH:some/path


